apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: node
          image: nginxinc/nginx-unprivileged
          # command: ["python3", "-c", "from flask import Flask, jsonify; app=Flask(__name__); \\n@app.route('/') \\ndef home(): return '<h1>Hello Flask V2</h1>'; \\n@app.route('/status') \\ndef status(): return jsonify(status='running', version='V2'); \\napp.run(host='0.0.0.0', port=8080)"]
          ports:
            - containerPort: 8080
