apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: node
          image: public.ecr.aws/nginx/nginx-unprivileged:stable-alpine3.21-slim
          ports:
            - containerPort: 8080
